FROM node:alpine

ENV API_URL=http://localhost:8000

RUN adduser -D frontend

WORKDIR /frontend
COPY ./frontend-example-docker/ ./

RUN chown -hR frontend .

USER frontend

RUN npm install

EXPOSE 5000

CMD ["npm","start"]
